# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 09f97ab1951a5921b97e90ad7c3b7e024d9c9aafaf32ce3c7fcd5e3be0895f6188ac14d7540d779ba699e7453ed0e842c2c9c43bc69c6767b9260769699fe619

test:
  secret_key_base: 6250ede461981d3c82f27c50836f011167a556af95a052599b0b916f9341b95e5c8b6a418f4165e252ffba8f6c5889730be930ddc1bcc949eb52cc1ee169dcfe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
